In [1]:
a = [1,2,3]
a[:0]

[]

In [2]:
a[:-1]

[1, 2]

In [3]:
a[-1:]

[3]

In [4]:
a[0]

1

In [5]:
a[-1:1]

[]

In [6]:
b=[]
b.append(a)

In [7]:
b

[[1, 2, 3]]

In [10]:
import numpy as np

In [11]:
a=np.array([])

In [12]:
b = np.array([1,2,3,4,5])

In [13]:
a
b

array([1, 2, 3, 4, 5])

In [14]:
a

array([], dtype=float64)

In [15]:
a = np.append(a,b)

In [16]:
a

array([1., 2., 3., 4., 5.])

In [17]:
c = np.array([1,2,3,4,5])
d = np.array([1,2,3,4,5])
a = np.append(b,c,d)
a

TypeError: only integer scalar arrays can be converted to a scalar index

In [18]:
a = np.append(a, np.append(b,c))

In [19]:
a

array([1., 2., 3., 4., 5., 1., 2., 3., 4., 5., 1., 2., 3., 4., 5.])

In [23]:
import numpy as np
a=np.array([[1,2,3,4],[4,5,6,7]])
b=np.array([1,3])
print(a)
print(b)

[[1 2 3 4]
 [4 5 6 7]]
[1 3]


In [21]:
a[range(2), range(1)]

array([1, 4])

In [22]:
a[range(2), [1, 3]]

array([2, 7])

In [24]:
a[range(2), b]

array([2, 7])

In [25]:
a[range(2), [b]]

array([[2, 7]])

In [17]:
a[range(2), range(1)]

SyntaxError: unexpected EOF while parsing (Temp/ipykernel_22076/158576230.py, line 1)

In [19]:
a[[1,1],[2,0]]

array([6, 4])

In [5]:
import pandas as pd

df = pd.DataFrame([{
    'a':1
    }])

print(df)

   a
0  1
